config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get "home/about" => "homes#about", as: "about"
  resources :users, only: [:show, :edit, :index, :update]
  resources :books, only: [:show, :edit, :index, :update, :new, :create, :destroy]

  devise_scope :user do
   post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 has_one_attached :image
 belongs_to :user
 validates :title, presence: true
 validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  def get_profile_image(width,height)
    unless profile_image.attached?
     file_path = Rails.root.join('app/assets/images/no_image.jpg')
     profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width,height]).processed
  end
  validates :name, presence:true, length: {minimum: 2, maximum: 20}, uniqueness:true
  validates :introduction, length: {maximum: 50}
 
  def self.guest
   find_or_create_by!(name:'guestuser',email:'guest@example.com') do |user|
    user.password = SecureRandom.urlsafe_base64
    user.name = "guestuser"
   end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 before_action :configure_permitted_parameters, if: :devise_controller?
 protected

  def after_sign_in_path_for(resource)
  user_path(current_user)
  end

  def after_sign_out_path_for(resource)
  root_path
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email]) # 注目
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :correct_user, only: [:edit, :update]

 def index
  @books = Book.all
  @book = Book.new
 end

 def create
  @book = Book.new(book_params)
  @book.user_id = current_user.id
  if @book.save
   flash[:notice] = "You have created book successfully."
   redirect_to book_path(@book.id)
   flash[:notice] = "successfully"
  else
   @books = Book.all
   flash[:alret] = "Error"
   render :'books/index'
  end
 end

 def show
  @book = Book.find(params[:id])
  @books = Book.all
  @user = @book.user
  @book_new = Book.new
 end

 def edit
  @books = Book.all
  @book = Book.find(params[:id])
 end

  def update
  @book = Book.find(params[:id])
  @book.update(book_params)
  #redirect_to book_path(@book.id)
   if @book.save
   flash[:notice] = "You have updated book successfully."
   redirect_to book_path(@book.id)
   flash[:notice] = "successfully"
   else
   @books = Book.all
   flash[:alret] = "Error"
   render :'books/edit'
   end
  end

 def destroy
  @book = Book.find(params[:id])
  if @book.destroy
  redirect_to books_path
  flash[:notice] = "successfully"
  end
 end

 private
 def book_params
 params.require(:book).permit(:title,:body)
 end

 def correct_user
  @book = Book.find(params[:id])
  @user = @book.user
  redirect_to(books_path) unless @user == current_user
 end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
 def guest_sign_in
  user = User.guest
  sign_in user
  redirect_to user_path(user),notice:'guestuserでログインしました。'
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!, except: [:top, :about]
 def index
  @book = Book.new
  @users = User.all
  @user = current_user
 end

 def show
  @book = Book.new
  @user = User.find(params[:id])
  @books = @user.books
 end

 def edit
  @user = User.find(params[:id])
  if @user == current_user
     render "edit"
  else
     redirect_to user_path(current_user.id)
  end
 end

 def update
  @user = User.find(params[:id])
  if @user.update(user_params)
  redirect_to user_path(@user.id)
  flash[:notice] = "successfully"
  else
   render :edit
  end
 end

 private
 def user_params
 params.require(:user).permit(:name, :introduction, :profile_image)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
   <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
   <% end %>
  </ul>
<% end %>

<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h1>Editing Book</h1>
   <%= render 'layouts/errors', obj: @book %>
   <%= form_with model: @book do |f| %>
<div class="form-group">
 <label for= "book_title">Title</label>
 <div><%= f.text_field :title %></div>
 </div>

 <div class="form-group">
 <label for= "book_opinion">Opinion</label>
 <div><%= f.text_area :body %></div>
 </div>

 <div class="form-group">
 <%= f.submit 'Update Book', class: "btn btn-success" %>
 </div>
<%= link_to "Show", book_path(@book.id) %>
|
<%= link_to "Back", books_path %>
<% end %>
</div>
</div>
<div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
   <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
   <% end %>
  </ul>
<% end %>

<main>
  <div class="container px-5 px-sm-0">
   <div class="row">
   <div class="col-md-3">
   <h2>User Info</h2>
   <%= image_tag current_user.get_profile_image(100,100) %>
   <table class="table">
    <tbody>
     <tr></tr>
     <tr>
      <th>name</th>
      <th><%= current_user.name %></th>
     </tr>
     <tr>
      <th>introduction</th>
      <th><%= current_user.introduction %></th>
     </tr>
    </tbody>
   </table>

    <div>
     <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary btn-block" do %>
     <i class= "fas fa-user-cog"></i>
     <% end %>
    </div>
     <h2 class="mt-3">New book</h2>
     <%= form_with model: @book do |f| %>
    <div class="form-group">
     <label for="book_title">Title</label>
     <div><%= f.text_field :title %></div>
    </div>
    <div class="form-group">
     <label for="book_opinion">Opinion</label>
     <div><%= f.text_area :body %></div>
    </div>
    <div class="form-group">
    <div class="col-md-8 offset-md-1">
    <%= f.submit 'Create Book', class: "btn btn-success" %>
    </div>
    </div>
    <% end %>
    </div>



<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hover table-inverse">
 <thead>
<tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
</tr>
</thead>
<tbody>
<% @books.each do |book| %>
<tr>
<td> <%= link_to user_path(book.user) do %>
      <%= image_tag book.user.get_profile_image(80,80) %>
    <% end %>
</td>
<td>
<%= link_to book_path(book.id) do %>
<%= book.title %>
<% end %>
</td>

<td><%= book.body %></td>
</tr>
<% end %>
</tbody>
</table>
</div>

</div>
</div>
</main>

app/views/books/show.html.erb
<% if @book.errors.any? %>
 <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
  <% @book.errors.full_messages.each do |message| %>
  <li><%= message %></li>
 <% end %>
  </ul>
<% end %>

 <div class="container">
  <div class="row">
   <div class="col-md-3">
   <h2>User Info</h2>
   <table class="table">
    <tbody>
   <tr></tr>
   <tr>
   <th>name</th>
   <th><%= @user.name %></th>
   </tr>
   <tr>
   <th>introduction</th>
   <th><%= @user.introduction %></th>
   </tr>
    </tbody>
   </table>

  <div class="row">
  <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
  <i class= "fas fa-user-cog"></i>
  <% end %>
  </div>
  <h2 class="mt-3">New book</h2>
  <%= form_with model: @book_new do |f| %>
  <div class="form-group">
  <label for="book_title">Title</label>
  <div><%= f.text_field :title %></div>
  </div>
  <div class="form-group">
  <label for="book_opinion">Opinion</label>
  <div><%= f.text_area :body %></div>
  </div>
  <div class="form-group">
  <%= f.submit 'Create Book', class: "btn btn-success" %>
  </div>
<% end %>

 </div>

 <div class="col-md-8 offset-md-1">
 <h2>Book detail</h2>
 <table class="table">
 <tbody>
 <tr>
 <td><%= link_to user_path(@book.user) do %>
  <%= image_tag @book.user.get_profile_image(80,80) %>
  <br>
  <%= @book.user.name %>
  <% end %>
 </td>
 <td>
 <%= link_to book_path(@book.id) do %>
 <%= @book.title %>
 <% end %>
 </td>
<td><%= @book.body %></td>
<% if @book.user == current_user %>
<td>
<%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %>
</td>
<td>
<%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-danger" %>
</td>
<% end %>

  </tr>
 </tbody>
 </table>
</div>
</div>
</div>

app/views/homes/about.html.erb
<!DOCTYPE html>
<title>Bookers2Ver2</title>
<main>
<p id="notice"></p>
   <div class="container">
   <div class="row">
    <h1 class="px-3 mx-auto">
       Welcome to
     <i class= "fas fa-book"></i>
     <strong>Bookers</strong>
      !
   </h1>
  </div>
 </div>
</main>

app/views/homes/top.html.erb
<main>
<div class="container">
 <div class="row">
  <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

    <h1>welcome to
    <i class= "fas fa-book"></i>
     <strong>Bookers</strong>
     !!
    </h1>
     <p>In
     <i class= "fas fa-book"></i>
      <strong>Bookers</strong>
         ,
     </p>
     <p>you can share and exchange your opinions , inpressions , and emotions</p>
     <p>about various books!</p>

     <div class="btn-wrapper col-10 mx-auto">
     <div class="row">
      <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block mb-3 sign_in", method: :post %>
     </div>
     <div class="row">
      <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
     </div>
     <div class="row">
      <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
     </div>
    </div>
   </div>
  </div>
 </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">

        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>

        <li>
         <%= link_to user_path(current_user), class: "nav-link text-light" do %>
         <i class= "fas fa-home"></i>Home
         <% end %>
        </li>
        <li>
         <%= link_to users_path, class: "nav-link text-light" do %>
         <i class= "fas fa-users"></i>Users
         <% end %>
        </li>
        <li>
         <%= link_to books_path, class: "nav-link text-light" do %>
         <i class= "fas fa-book-open"></i>Books
         <% end %>
        </li>
        <li>
        <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
        <i class= "fas fa-sign-out-alt"></i>Log out
        <% end %>
        </li>
        <% else %>
        <li>
        <%= link_to root_path, class: "nav-link text-light" do %>
        <i class="fas fa-home"></i>Home
        <% end %>
        </li>
        <li>
        <%= link_to about_path, class: "nav-link text-light" do %>
        <i class= "fas fa-link"></i>About
        <% end %>
        </li>
        <li>
        <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
        <i class="fas fa-user-plus"></i>Sign up
        <% end %>
        </li>
        <li>
        <%= link_to new_user_session_path, class: "nav-link text-light" do %>
        <i class="fas fa-sign-in-alt"></i>Log in
         <% end %>
        </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
   </header>
    <%= flash[:notice] %>
    <%= yield %>
    <footer>
 <div class="container mt-5">
  <div class="row">
   <div class="mx-auto">
    <p>CopyRight Infratop.inc</p>
   </div>
  </div>
 </div>
</footer>
  </body>
</html>

app/views/layouts/notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: #{key}) %>
<% end %>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <ul>
   <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
   <% end %>
  </ul>
<% end %>

        <main>
        <p id="notice"></p>
        <div class="container">
        <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <%= form_with model: @user do |f| %>
        <div class="form-group">
        <label for="user_name">Name</label>
         </div>
         <%= f.text_field :name %>
         <div class="form-group">
          <label for="user_image">Image</label>
         </div>
         <%= f.file_field :profile_image, accept: "image/*" %>

         <div class="form-group">
         <label for="user_introduction">Introduction</label>
         </div>
          <%= f.text_area :introduction %>
         <div class="form-group">
          <%= f.submit 'Update User' , class: "btn btn-secondary" %>
          <% end %>
         </div>
        </div>
       </div>
      </div>
    </main>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class= "row">
    <div class= "col-md-3">
      <h2>User info</h2>
      <%= image_tag @user.get_profile_image(100,100) %>
      <table class="table">
      <tbody>
      <tr>
      <th>name</th>
      <th><%= @user.name %></th>
      </tr>
       <tr>
      <th>introduction</th>
      <th><%= @user.introduction %></th>
      </tr>
      </tbody>
      </table>



       <div class="row">
      <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary btn-block" do %>
      <i class= "fas fa-user-cog"></i>
     <% end %>
     </div>

      <h2 class="mt-3">New book</h2>
      <!-- form_with部分 -->
      <%= form_with model: Book.new do |f| %>
        <label for="book_title">Title</label>
        <div><%= f.text_field :title %></div>
        <label for="book_opinion">Opinion</label>
        <div><%= f.text_area :body %></div>

        <%= f.submit 'Create Book', class: "btn btn-success" %>
      <% end %>
    </div>
    <div class= "col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
       <thead>
        <tr>
         <th>image</th>
         <th>name</th>
         <th></th>
        </tr>
       </thead>
       <tbody>
         <% @users.each do |user| %>
         <tr>
         <td><%= image_tag @user.get_profile_image(80,80) %></td>
         <td><%= user.name %></td>
         <td><%= link_to "Show", user_path(user.id) %></td>
         </tr>
      <% end %>
      </tbody>
     </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
 <div class="container px-5 px-sm-0">
  <div class="row">
   <div class="col-md-3">
    <h2>User Info</h2>
    <%= image_tag @user.get_profile_image(100,100) %>
     <table class="table">
      <tbody>
       <tr></tr>
       <tr>
        <th>name</th>
        <th><%= @user.name %></th>
       </tr>

       <tr>
        <th>introduction</th>
        <th>
        <%= @user.introduction %>
        </th>
       </tr>
      <tbody>
     </table>



       <% if @user.name != "guestuser" %>
       <div class='row'>
      <%= link_to '',edit_user_path(@user.id),class: "btn btn-outline-secondary" %>
       </div>
      <% end %>




     <h2 class="mt-3">New book</h2>
     <form action="/books" accept-charset="UTF-8" method="post">
     <%= form_with model: @book do |f| %>
      <div class="form-group">
       <label for="book_title">Title</label>
       <div><%= f.text_field :title %></div>
      </div>

      <div class="form-group">
       <label for="book_opinion">Opinion</label>
       <div><%= f.text_area :body %></div>
      </div>

      <div class="form-group">
       <%= f.submit 'Create Book', class: "btn btn-success" %>
       <% end %>
       </form>
      </div>
     </div>

     <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
      <thead>
       <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
       </tr>
      </thead>

      <tbody>
       <% @books.each do |book| %>
       <tr>
        <td><%= link_to user_path(book.user.id) do %>
        <%= image_tag book.user.get_profile_image(80,80) %>
        <% end %>
        </td>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
       </tr>
        <% end %>
      </tbody>
     </table>
    </div>
   </div>
  </div>